### ISSUE TITLE
manifest v2

### ISSUE THREAD

**Issue by bgotink** [bgotink/IngressIdentity#26]
todo list:
- [x] ~~#23 add a 'version' column to manifests~~
- [x] ~~#13 allow users to set trust level~~
- [x] #24 remove 'extratags'
- [x] #25 remove necessity superfluous columns in source files
- [x] #27 allow local source urls
- [x] ...
